=== rd2/tbd/tbd.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://github.com/rd2/tbd/blob/master/tbd.schema.json",
  "title": "TBD Schema",
  "description": "Schema for Thermal Bridging and Derating",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "schema": {
      "type": "string"
    },
    "psis": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/PSI"
      },
      "uniqueItems": true
    },
    "khis": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/KHI"
      },
      "uniqueItems": true
    },
    "edges": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Edge"
      },
      "uniqueItems": true
    },
    "subsurfaces": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/SubSurface"
      },
      "uniqueItems": true
    },
    "surfaces": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Surface"
      },
      "uniqueItems": true
    },
    "spaces": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Space"
      },
      "uniqueItems": true
    },
    "spacetypes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/SpaceType"
      },
      "uniqueItems": true
    },
    "stories": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Story"
      },
      "uniqueItems": true
    },
    "building": {
      "type": "object",
      "$ref": "#/definitions/Building"
    },
    "log": {
      "type": "object",
      "$ref": "#/definitions/Log"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "PSI": {
      "description": "Set of PSI-values (in W/K per m) for thermal bridges",
      "type": "object",
      "properties": {
        "id": {
          "title": "Unique PSI set identifier",
          "type": "string"
        },
        "rimjoist": {
          "title": "Floor/wall edge PSI",
          "type": "number"
        },
        "rimjoistconcave": {
          "title": "Concave floor/wall edge PSI",
          "type": "number"
        },
        "rimjoistconvex": {
          "title": "Convex floor/wall edge PSI",
          "type": "number"
        },
        "parapet": {
          "title": "Roof/wall edge PSI",
          "type": "number"
        },
        "parapetconcave": {
          "title": "Concave roof/wall edge PSI",
          "type": "number"
        },
        "parapetconvex": {
          "title": "Convex roof/wall edge PSI",
          "type": "number"
        },
        "fenestration": {
          "title": "Window, door, skylight perimeter PSI",
          "type": "number"
        },
        "head": {
          "title": "Aperture head/lintel PSI",
          "type": "number"
        },
        "headconcave": {
          "title": "Concave aperture head/lintel PSI",
          "type": "number"
        },
        "headconvex": {
          "title": "Convex aperture head/lintel PSI",
          "type": "number"
        },
        "sill": {
          "title": "Aperture sill/base PSI",
          "type": "number"
        },
        "sillconcave": {
          "title": "Concave aperture sill/base PSI",
          "type": "number"
        },
        "sillconvex": {
          "title": "Convex aperture sill/base PSI",
          "type": "number"
        },
        "jamb": {
          "title": "Aperture jamb/side PSI",
          "type": "number"
        },
        "jambconcave": {
          "title": "Concave aperture jamb/side PSI",
          "type": "number"
        },
        "jambconvex": {
          "title": "Convex aperture jamb/side PSI",
          "type": "number"
        },
        "corner": {
          "title": "Any wall corner [0°,135°) or (225°,360°] PSI",
          "type": "number"
        },
        "cornerconcave": {
          "title": "Concave wall corner [0°,135°) PSI",
          "type": "number"
        },
        "cornerconvex": {
          "title": "Convex wall corner (225°,360°] PSI",
          "type": "number"
        },
        "balcony": {
          "title": "Floor/balcony edge PSI ",
          "type": "number"
        },
        "balconyconcave": {
          "title": "Concave floor/balcony edge PSI ",
          "type": "number"
        },
        "balconyconvex": {
          "title": "Convex floor/balcony edge PSI ",
          "type": "number"
        },
        "party": {
          "title": "Party wall edge PSI",
          "type": "number"
        },
        "partyconcave": {
          "title": "Concave party wall edge PSI",
          "type": "number"
        },
        "partyconvex": {
          "title": "Convex party wall edge PSI",
          "type": "number"
        },
        "grade": {
          "title": "Floor/foundation edge PSI",
          "type": "number"
        },
        "gradeconcave": {
          "title": "Concave floor/foundation edge PSI",
          "type": "number"
        },
        "gradecovex": {
          "title": "Convex floor/foundation edge PSI",
          "type": "number"
        },
        "joint": {
          "title": "Joints PSI",
          "type": "number"
        },
        "transition": {
          "title": "(Mild) transition PSI",
          "type": "number"
        }
      },
      "additionalProperties": false,
      "minProperties": 2,
      "required": [
        "id"
      ]
    },
    "KHI": {
      "description": "KHI-value (in W/K) for a point thermal bridge",
      "type": "object",
      "properties": {
        "id": {
          "title": "Unique KHI identifier",
          "type": "string"
        },
        "point": {
          "title": "Point KHI-value",
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "point"
      ]
    },
    "Edge": {
      "description": "Surface(s) edge as thermal bridge",
      "type": "object",
      "properties": {
        "psi": {
          "title": "PSI-set identifier",
          "type": "string"
        },
        "type": {
          "title": "PSI-set type e.g., 'parapet'",
          "type": "string",
          "enum": [
            "rimjoist",
            "rimjoistconcave",
            "rimjoisconvext",
            "parapet",
            "parapetconcave",
            "parapetconvex",
            "fenestration",
            "head",
            "headconcave",
            "headconvex",
            "sill",
            "sillconcave",
            "sillconvex",
            "jamb",
            "jambconcave",
            "jambconvex",
            "corner",
            "cornerconcave",
            "cornerconvex",
            "balcony",
            "balconyconcave",
            "balconyconvex",
            "party",
            "partyconcave",
            "partyconvex",
            "grade",
            "gradeconcave",
            "gradeconvex",
            "joint",
            "transition"
          ]
        },
        "length": {
          "title": "Edge length (m), > 0 m",
          "type": "number",
          "minimum": 0,
          "exclusiveMinimum": true
        },
        "v0x": {
          "title": "Edge origin X vertex (m)",
          "type": "number"
        },
        "v0y": {
          "title": "Edge origin Y vertex (m)",
          "type": "number"
        },
        "v0z": {
          "title": "Edge origin Z vertex (m)",
          "type": "number"
        },
        "v1x": {
          "title": "Edge terminal X vertex (m)",
          "type": "number"
        },
        "v1y": {
          "title": "Edge terminal Y vertex (m)",
          "type": "number"
        },
        "v1z": {
          "title": "Edge terminal Z vertex (m)",
          "type": "number"
        },
        "surfaces": {
          "title": "Surface(s) connected to edge",
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      },
      "additionalProperties": false,
      "required": [
        "type",
        "surfaces"
      ]
    },
    "SubSurface": {
      "description": "Suburface(s) U-factors (optional)",
      "type": "object",
      "properties": {
        "id": {
          "title": "e.g. OS or E+ surface identifier",
          "type": "string"
        },
        "usi": {
          "title": "Overall U-factor",
          "type": "number",
          "minimum": 0.01,
          "maximum": 10.0
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "usi"
      ]
    },
    "Surface": {
      "description": "Surface default PSI-set (optional)",
      "type": "object",
      "properties": {
        "id": {
          "title": "e.g. OS or E+ surface identifier",
          "type": "string"
        },
        "psi": {
          "title": "PSI-set identifier",
          "type": "string"
        },
        "khis": {
          "title": "Surface-hosted point thermal bridges",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "title": "Unique KHI-value identifier",
                "type": "string"
              },
              "count": {
                "title": "Number of KHI-matching point thermal bridges",
                "type": "number",
                "minimum": 1
              }
            },
            "additionalProperties": false,
            "required": [
              "id",
              "count"
            ]
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false,
      "minProperties": 2,
      "required": [
        "id"
      ]
    },
    "Space": {
      "description": "Space default PSI-set (optional for OS)",
      "type": "object",
      "properties": {
        "id": {
          "title": "e.g. OS space or E+ zone identifier",
          "type": "string"
        },
        "psi": {
          "title": "PSI-set identifier",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "psi"
      ]
    },
    "SpaceType": {
      "description": "SpaceType default PSI-set (optional for OS)",
      "type": "object",
      "properties": {
        "id": {
          "title": "e.g. OS spacetype identifier",
          "type": "string"
        },
        "psi": {
          "title": "PSI-set identifier",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "psi"
      ]
    },
    "Story": {
      "description": "Story default PSI-set (optional for OS)",
      "type": "object",
      "properties": {
        "id": {
          "title": "e.g. OS story identifier",
          "type": "string"
        },
        "psi": {
          "title": "PSI-set identifier",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "psi"
      ]
    },
    "Building": {
      "description": "Building default PSI-set (optional for OS)",
      "type": "object",
      "properties": {
        "psi": {
          "title": "PSI-set identifier",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "psi"
      ]
    },
    "Log": {
      "description": "TBD log",
      "type": "object",
      "properties": {
        "date": {
          "title": "Timestamp",
          "type": "string"
        },
        "status": {
          "title": "Global state",
          "type": "string"
        },
        "ua": {
          "title": "UA' assessment",
          "type": "object",
          "properties": {
            "bloc1": {
              "title": "heating setpoints >= 18°C",
              "type": "object",
              "$ref": "#/definitions/UaBlock"
            },
            "bloc2": {
              "title": "heating setpoints < 18°C",
              "type": "object",
              "$ref": "#/definitions/UaBlock"
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        },
        "results": {
          "title": "Thermal derating results",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "messages": {
          "title": "Logged messages",
          "type": "array",
          "items": {
            "$ref": "#/definitions/LogMessage"
          }
        }
      },
      "additionalProperties": false
    },
    "LogMessage": {
      "description": "TBD log messages",
      "type": "object",
      "properties": {
        "level": {
          "title": "Severity of logged message (e.g. WARN)",
          "type": "string"
        },
        "message": {
          "title": "Logged message",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "UaBlock": {
      "description": "UA summary",
      "type": "object",
      "properties": {
        "summary": {
          "type": "string"
        },
        "walls": {
          "type": "string"
        },
        "roofs": {
          "type": "string"
        },
        "floors": {
          "type": "string"
        },
        "doors": {
          "type": "string"
        },
        "windows": {
          "type": "string"
        },
        "skylights": {
          "type": "string"
        },
        "rimjoists": {
          "type": "string"
        },
        "parapets": {
          "type": "string"
        },
        "trim": {
          "type": "string"
        },
        "corners": {
          "type": "string"
        },
        "grade": {
          "type": "string"
        },
        "other": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "minProperties": 2,
      "required": ["summary"]
    }
  }
}

=== rd2/tbd/json/tbd_smalloffice.json
{
  "schema": "https://github.com/rd2/tbd/blob/ua/tbd.schema.json",
  "description": "test_smalloffice.osm with building story PSI set",
  "psis": [{
    "id": "office PSI set",
    "rimjoist": 0.300,
    "parapet": 0.310,
    "fenestration": 0.320,
    "cornerconcave": 0.330,
    "cornerconvex": 0.340,
    "balcony": 0.350,
    "party": 0.360,
    "grade": 0.370
  }],
  "building": {
    "psi": "regular (BETBG)"
  },
  "stories": [{
    "id": "Building Story 1",
    "psi": "office PSI set"
  }]
}

=== rd2/tbd/json/tbd_warehouse6.json
{
  "schema": "https://github.com/rd2/tbd/blob/master/tbd.schema.json",
  "description": "testing expansion joints for test_warehouse.osm",
  "psis": [
    {
      "id": "ok",
      "joint": 0.9
    }
  ],
  "edges": [
    {
      "psi": "ok",
      "type": "joint",
      "surfaces": [
        "Fine Storage Front Wall",
        "Fine Storage Office Front Wall"
      ]
    },
    {
      "psi": "ok",
      "type": "joint",
      "surfaces": [
        "Fine Storage Left Wall",
        "Fine Storage Office Left Wall"
      ]
    }
  ]
}

=== rd2/tbd/json/tbd_5ZoneNoHVAC_btap.json
{
  "schema": "https://github.com/rd2/tbd/blob/master/tbd.schema.json",
  "description": "testing TBD JSON for 5ZoneNoHVAC",
  "psis": [
    {
      "id": "BTAP-ExteriorWall-Mass-6 good",
      "rimjoist": 0.02,
      "parapet": 0.23,
      "fenestration": 0.078,
      "corner": 0.09,
      "balcony": 0.2,
      "party": 0.2,
      "grade": 0.32,
      "joint": 0.1,
      "transition": 0.0
    },
    {
      "id": "BTAP-ExteriorWall-Mass-2 good",
      "rimjoist": 0.01,
      "parapet": 0.23,
      "fenestration": 0.078,
      "corner": 0.09,
      "balcony": 0.2,
      "party": 0.2,
      "grade": 0.32,
      "joint": 0.1,
      "transition": 0.0
    },
    {
      "id": "BTAP-ExteriorWall-Metal-1 good",
      "rimjoist": 0.03,
      "parapet": 0.35,
      "fenestration": 0.078,
      "corner": 0.07,
      "balcony": 0.2,
      "party": 0.2,
      "grade": 0.5,
      "joint": 0.1,
      "transition": 0.0
    },
    {
      "id": "BTAP-ExteriorWall-WoodFramed-5 good",
      "rimjoist": 0.03,
      "parapet": 0.05,
      "fenestration": 0.078,
      "corner": 0.04,
      "balcony": 0.2,
      "party": 0.2,
      "grade": 0.09,
      "joint": 0.1,
      "transition": 0.0
    },
    {
      "id": "BTAP-ExteriorWall-SteelFramed-1 good",
      "rimjoist": 0.09,
      "parapet": 0.35,
      "fenestration": 0.078,
      "corner": 0.09,
      "balcony": 0.2,
      "party": 0.2,
      "grade": 0.47,
      "joint": 0.1,
      "transition": 0.0
    }
  ],
  "spacetypes": [
    {
      "id": "Warehouse - fine",
      "psi": "BTAP-ExteriorWall-Mass-6 good"
    },
    {
      "id": "Audience - auditorium",
      "psi": "BTAP-ExteriorWall-Mass-2 good"
    },
    {
      "id": "Workshop space",
      "psi": "BTAP-ExteriorWall-Metal-1 good"
    },
    {
      "id": "Office - enclosed",
      "psi": "BTAP-ExteriorWall-WoodFramed-5 good"
    },
    {
      "id": "Sales area",
      "psi": "BTAP-ExteriorWall-SteelFramed-1 good"
    }
  ],
  "building": {
    "psi": "BTAP-ExteriorWall-Mass-2 good"
  }
}

=== rd2/tbd/_site/json/tbd_seb_n3.json
{
  "schema": "https://github.com/rd2/tbd/blob/master/tbd.schema.json",
  "description": "testing TBD JSON for seb.osm",
  "psis": [{
      "id": "good",
      "parapet": 0.5,
      "rimjoist": 0.9
    },
    {
      "id": "compliant",
      "rimjoist": 0.3,
      "parapet": 0.325,
      "fenestration": 0.35,
      "corner": 0.45,
      "balcony": 0.5,
      "party": 0.5,
      "grade": 0.45
    }
  ],
  "khis": [{
      "id": "column",
      "point": 0.5
    },
    {
      "id": "support",
      "point": 0.5
    }
  ],
  "surfaces": [{
    "id": "Entryway  Wall 5",
    "khis": [{
        "id": "column",
        "count": 3
      },
      {
        "id": "support",
        "count": 4
      }
    ],
    "psi": "good"
  }]
}

=== rd2/tbd/_site/json/tbd_seb_n4.json
{
  "schema": "https://github.com/rd2/tbd/blob/master/tbd.schema.json",
  "description": "testing TBD JSON for seb.osm",
  "psis": [{
      "id": "bad",
      "fenestration": 1.1
    },
    {
      "id": "good",
      "parapet": 0.5,
      "rimjoist": 0.9
    },
    {
      "id": "compliant",
      "rimjoist": 0.3,
      "parapet": 0.325,
      "fenestration": 0.35,
      "corner": 0.45,
      "balcony": 0.5,
      "party": 0.5,
      "grade": 0.45
    }
  ],
  "khis": [{
      "id": "column",
      "point": 0.0
    },
    {
      "id": "support",
      "point": 0.0
    }
  ],
  "building": {
    "psi": "(non thermal bridging)"
  },
  "surfaces": [{
    "id": "Entryway  Wall 5",
    "khis": [{
        "id": "column",
        "count": 3
      },
      {
        "id": "support",
        "count": 4
      }
    ],
    "psi": "(non thermal bridging)"
  }],
  "edges": [{
    "psi": "bad",
    "type": "fenestration",
    "surfaces": [
      "Entryway  Wall 5",
      "Sub Surface 8"
    ]
  }]
}

=== rd2/tbd/_site/json/tbd_PSI_combo2.json
{
  "schema": "https://github.com/rd2/tbd/blob/master/tbd.schema.json",
  "description": "TBD JSON example - combining building vs surface vs edge PSI sets",
  "psis": [{
      "id": "OK",
      "rimjoist": 0.7,
      "parapet": 0.7,
      "fenestration": 0.7,
      "corner": 0.7,
      "balcony": 1,
      "party": 0.7,
      "grade": 0.7
    },
    {
      "id": "Awesome",
      "rimjoist": 0.2,
      "parapet": 0.2,
      "fenestration": 0.2,
      "corner": 0.2,
      "balcony": 0.3,
      "party": 0.2,
      "grade": 0.2
    },
    {
      "id": "Party wall edge",
      "party": 0.4
    }
  ],
  "building": {
    "psi": "Awesome"
  },
  "surfaces": [{
    "id": "ground-floor restaurant South-wall",
    "psi": "ok"
  }],
  "edges": [{
    "psi": "Party wall edge",
    "type": "party",
    "length": 4.3,
    "surfaces": [
      "ground-floor restaurant West-wall",
      "ground-floor restaurant party wall"
    ]
  }]
}

=== rd2/tbd/json/tbd_warehouse9.json
{
  "schema": "https://github.com/rd2/tbd/blob/master/tbd.schema.json",
  "description": "testing error detection",
  "psis": [{
      "id": "detailed_2",
      "fenestration": 0.600
    },
    {
      "id": "regular (BETBG)",
      "fenestration": 0.700
    }
  ],
  "khis": [{
    "id": "cantilevered beam",
    "point": 0.6
  }],
  "surfaces": [{
      "id": "Office Front Wall",
      "khis": [{
        "id": "beam",
        "count": 3
      }]
    },
    {
      "id": "Office Left Wall",
      "khis": [{
        "id": "cantilevered beam",
        "count": 300
      }]
    }
  ],
  "edges": [{
    "psi": "detailed",
    "type": "fenestration",
    "surfaces": [
      "Office Front Wall",
      "Office Front Wall Window 1"
    ]
  }]
}

=== rd2/tbd/json/tbd_json_test.json
{
  "schema": "https://github.com/rd2/tbd/blob/logger/tbd.schema.json",
  "description": "testing basic JSON validation",
  "psis": [
    {
      "id": "good",
      "parapet": 0.5,
      "party": 0.9
    },
    {
      "id": "compliant",
      "rimjoist": 0.3,
      "parapet": 0.325,
      "fenestration": 0.35,
      "corner": 0.45,
      "balcony": 0.5,
      "party": 0.5,
      "grade": 0.45
    }
  ],
  "khis": [
    {
      "id": "column",
      "point": 0.5
    },
    {
      "id": "support",
      "point": 0.5
    }
  ],
  "edges": [
    {
      "psi": "compliant",
      "type": "party",
      "length": 2.5,
      "surfaces": [
        "front wall"
      ]
    }
  ],
  "surfaces": [
    {
      "id": "front wall",
      "khis": [
        {
          "id": "column",
          "count": 3
        },
        {
          "id": "support",
          "count": 4
        }
      ],
      "psi": "good"
    }
  ],
  "building": {
    "psi": "compliant"
  }
}
